multi-step-survey
SarahWett/capstone-project pull request #8
Opened 2023-03-07 14:03 UTC by SarahWett

**What's new:**

- multi-step-form including 3 questions aka pages 
- added smiley svg's in public (not used in form yet) 
- cancel button in nav-bar 
- Prev / Next Button 
- Texture saving text as you leave page 

**Comments:**

- Submit-Button yet displays Alert Message to give visual Feedback 
- The multistep-form accidentally includes 3 User stories ( [US 2](https://github.com/SarahWett/capstone-project/issues/2) | [US 3](https://github.com/SarahWett/capstone-project/issues/6) | [US 4](https://github.com/SarahWett/capstone-project/issues/3) ) 
- The Questions 1 & 2 don't work out to save data while switching pages - can't figure out how to get it work until now (ISSUE!)

2023-03-07 14:36 UTC, TuncAlt requested changes
i hope this code example will help you

2023-03-07 14:36 UTC, TuncAlt commented on components/QuestionTwo/index.js
> +  const [isChecked, setIsChecked] = useState(false);
maybe you have to put all checkboxes into a state?
The onChange function for all the checkboxes is almost identical. You should extract this into a separate function to reduce code duplication? 

like so: 

export default function Tags({ formData, setFormData }) {
  const [familyChecked, setFamilyChecked] = useState(false);
 
 const handleCheckboxChange = (name, isChecked) => {
    setFormData({ ...formData, [name]: isChecked });
  };

  return (
    <>
      <label htmlFor="family">Family</label>
      <input
        type="checkbox"
        id="family"
        name="family"
        checked={familyChecked}
        onChange={(event) => {
          setFamilyChecked(event.target.checked);
          handleCheckboxChange("family", event.target.checked);
        }}
      />

2023-03-07 16:50 UTC, Kheirah requested changes
Really good!

Take a look at the comments and try restoring the values that are selected in step 1, 2 and 3. Right now, when I navigate between the steps I lose my selections. Better implement it now since you won't get passed the QA without it anyway :)

2023-03-07 16:50 UTC, Kheirah commented on components/Form/index.js
> +            </button>
- Your `button` needs a `type`. 
- Your `onClick` doesn't need to prevent anything since it's not a submit event.

2023-03-07 16:50 UTC, Kheirah commented on components/Form/index.js
> +            </button>
The same is true of this `button`.

2023-03-07 16:50 UTC, Kheirah commented on components/Header/index.js
> +  z-index: 102; */
Don't leave comments in the PR. Either use the styling in this case or remove it.

2023-03-07 16:50 UTC, Kheirah commented on components/QuestionTwo/index.js
> +  };
Not sure what this is doing. It's toggling a boolean value, yes. But what use is it?
In case you wanted to keep track of which selections were made when navigating between the steps, try again. It's not yet working 😄

2023-03-08 09:17 UTC, SarahWett commented on components/Form/index.js
> +            </button>
Fixed!

2023-03-08 09:17 UTC, SarahWett commented on components/Form/index.js
> +            </button>
Fixed!

2023-03-08 09:17 UTC, SarahWett commented on components/Header/index.js
> +  z-index: 102; */
Fixed! :)

2023-03-08 11:37 UTC, SarahWett commented on components/QuestionTwo/index.js
> +  const [isChecked, setIsChecked] = useState(false);
thank you! 
Finally found a solution - thanks for your time! <3

2023-03-08 11:50 UTC, bk1405bgl commented
> **What's new:**
> 
> * multi-step-form including 3 questions aka pages
> * added smiley svg's in public (not used in form yet)
> * cancel button in nav-bar
> * Prev / Next Button
> * Info is saved while switching pages
> 
> **Comments:**
> 
> * Submit-Button yet only displays Alert Message to give visual Feedback
> * The multistep-form accidentally includes 3 User stories ( [US 2](https://github.com/SarahWett/capstone-project/issues/2) | [US 3](https://github.com/SarahWett/capstone-project/issues/6) | [US 4](https://github.com/SarahWett/capstone-project/issues/3) )
> * PLS check Question No.2 : I didn't use formData / setFormData as I did in question 1 & 2 - but it works out saving the value to a local storage.. do you have any suggestions how to do this including formData ? :)

Do the formData / setFormData in Q2 as in Q1.

2023-03-08 11:50 UTC, bk1405bgl approved these changes

2023-03-08 13:41 UTC, merged